# Generated by Django 5.2.6 on 2025-09-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundoimobiliario',
            old_name='dividend_yield_dedio_12m',
            new_name='dividend_yield_medio_12m',
        ),
        migrations.AlterField(
            model_name='fundoimobiliario',
            name='setor',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('hotel', 'Hotel'), ('hibrido', 'Híbrido'), ('lajes_corporativas', 'Lajes Corporativas'), ('logistica', 'Logística'), ('outros', 'Outros'), ('residencial', 'Residencial'), ('titulos_valores_mobiliarios', 'Títulos e Val. Mob.')], max_length=30),
        ),
    ]
